spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ponditjwtauth
    username: shuvo
    password: Alpha@123
    driver-class-name: com.mysql.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  token-validity: 180000

server:
  port: 8888